apiVersion: v1
kind: ConfigMap
metadata:
  name: weblexonclient-config
data:
  config.js: |
    window.REACT_APP_ENVIRONMENT='PROD'
    window.API_CENTINELA_GATEWAY =  'https://lexbox-test-apigwcen.lefebvre.es/api/v1/cen/Centinela';
