{{- $name := include "userutils-api.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $gwlex := include "url-of" (list .Values.app.ingress.entries.lexonapigw .) -}}
{{- $cen := include "url-of" (list .Values.app.ingress.entries.centinelaapi .) -}}
{{- $lex := include "url-of" (list .Values.app.ingress.entries.lexonapi .) -}}
{{- $sig := include "url-of" (list .Values.app.ingress.entries.signatureapi .) -}}
{{- $clientsig := include "url-of" (list .Values.app.ingress.entries.signature .) -}}
{{- $mongo := include "mongo-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "userutils-api.name" . }}
    chart: {{ template "userutils-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    env: {{ .Values.lef.env }}
    version: {{ .Chart.Version | quote }}
data:
  urls__IdentityUrl: http://{{ $identity }}
  urls__IdentityUrlExternal: http://{{ $identity }}
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  userutils__ConnectionString: mongodb://{{ $mongo }}
  userutils__Database: {{ .Values.inf.mongo.centinela.database }}
  userutils__TokenCaducity: {{ .Values.userutils.token.caducity | quote}}
  userutils__TokenKey: {{ .Values.userutils.token.key | quote}}
  all__Version: {{ .Chart.Version | quote }}
  urls__HubUrlExternal: https://{{ .Values.svchub.url }}/Herramientas/get
  urls__OnlineUrlExternal: http://{{ .Values.svconline.url }}/webcliente46/ws
  all__OnlineLogin: {{ .Values.svconline.login | quote }}
  all__OnlinePass: {{ .Values.svconline.pass | quote }}
  urls__ComToolsUrlExternal: http://{{ .Values.svccomtools.url }}
  urls__ClavesUrlExternal: https://{{ .Values.svcclaves.url }}
  urls__LexonApi: http://{{ .Values.app.ingress.entries.lexonapi }}/api/v1/Lexon
  urls__SignatureApi: http://{{ .Values.app.ingress.entries.signatureapi }}/api/v1/Signaturit
  urls__CentinelaApi: http://{{ .Values.app.ingress.entries.centinelaapi }}/api/v1/Centinela
  urls__Signature: https://{{ .Values.app.ingress.entries.signature }}
  urls__ByPassLexOnId: {{ .Values.userutils.bypass.lex.id | quote}}
  urls__ByPassLexOnUrl: 'https://{{ $gwlex }}/utils/UserUtils/user/apps/redirect?NameService={serviceName}&idUser={idUserNavision}'
  # urls__ByPassLexOnUrl_bis: 'https://{{ .Values.userutils.bypass.lex.url }}'
  urls__ByPassSigId: {{ .Values.userutils.bypass.sig.id | quote}}
  urls__ByPassSigUrl: 'https://{{ .Values.app.ingress.entries.signature }}/access/{tokenSignature}'
  # urls__ByPassSigUrl_bis: 'https://{{ .Values.userutils.bypass.sig.url }}'

