# Stage 1
FROM node:8 as react-build
WORKDIR /app
COPY . ./
RUN yarn
RUN yarn build

# Stage 2 - the production environment
FROM nginx:alpine
#COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./google_client.pem /etc/nginx/conf.d/google_client.pem
COPY ./google_client_key.pem /etc/nginx/conf.d/google_client_key.pem
COPY ./google_client_key_pass.txt /etc/nginx/conf.d/google_client_key_pass.txt
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/build /usr/share/nginx/html
RUN ls -lha /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
