version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  webstatus:
    image: ${REGISTRY:-elefebvreoncontainers}/webstatuslef:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebStatusLef/Dockerfile
      
  webportalclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webportalclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebPortalClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  webgoogleclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webgoogleclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebGoogleClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  webofficeclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webofficeclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebOffice365Client/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq
     
  weblexonclient:
    image: ${REGISTRY:-elefebvreoncontainers}/weblexonclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebLexonClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

 # webloginaddonlexon:
 #   image: ${REGISTRY:-elefebvreoncontainers}/webloginaddonlexon:${PLATFORM:-linux}-${TAG:-dev}
 #   build:
 #     context: .
 #     dockerfile: src/Web/WebLoginAddonLexon/Dockerfile    
 #     args:
 #       NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
 #   depends_on:
 #     - rabbitmq     

  account.api:
    image: ${REGISTRY:-elefebvreoncontainers}/account.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  webaccountapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - account.api

  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq
      - lexon.api

  weblexonapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - lexon.api
      - lexon.mysql.api
      
  webimapclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webimapclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebImapClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq      