version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    image: ${REGISTRY:-elefebvre}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data
  
  webportalclient:
    image: ${REGISTRY:-elefebvre}/webportalclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebPortalClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  webgoogleclient:
    image: ${REGISTRY:-elefebvre}/webgoogleclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebGoogleClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  webofficeclient:
    image: ${REGISTRY:-elefebvre}/webofficeclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebOffice365Client/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  account.api:
    image: ${REGISTRY:-elefebvre}/account.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webaccountapigw:
    image: ${REGISTRY:-elefebvre}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - account.api

  lexon.api:
    image: ${REGISTRY:-elefebvre}/lexon.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvre}/lexon.mysql.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq
      - lexon.api

  weblexonapigw:
    image: ${REGISTRY:-elefebvre}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - account.api
      - lexon.api
      - lexon.mysql.api