version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile    


  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - lexon.mysql.api

  account.api:
    image: ${REGISTRY:-elefebvreoncontainers}/account.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile

  lexonapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/lefebvre.gw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - lexon.api

  accountgw:
    image: ${REGISTRY:-elefebvreoncontainers}/lefebvre.gw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - account.api

#  webstatus:
#    image: ${REGISTRY:-paconaf}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
#    build:
#      context: .
#      dockerfile: src/Web/WebStatusLefebvre/Dockerfile
#  