version: '3'

services:

  reverse-proxy:
    image: traefik:1.7.13
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  imap-server:
    image: avalverdelefebvre/react-imapsmtp-docker:server-latest
    ports:
      - "9010:9010"
    labels:
      - traefik.backend=lefebvre-imap-smtp-server
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  imap-client:
    image: avalverdelefebvre/react-imapsmtp-docker:client-newdesign-latest
    ports:
      - "8081:80"
    labels:
      - traefik.backend=lefebvre-imap-smtp-client
      - "traefik.frontend.rule=PathPrefixStrip:/"  

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8084:80"       
      
  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - lexon.mysql.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8085:80"       

  account.api:
    image: ${REGISTRY:-elefebvreoncontainers}/account.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8088:80"      

  lexonapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelot.gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - lexon.mysql.api
      - lexon.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - LexonMySqlUrlHC=http://lexon.mysql.api/hc
      - AccountsUrlHC=http://accounts.api/hc
    ports:
      - "8086:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Lexon/apigw:/app/configuration
      
  accountgw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelot.gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - account.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - LexonMySqlUrlHC=http://lexon.mysql.api/hc
      - AccountsUrlHC=http://accounts.api/hc
    ports:
      - "8083:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Account/apigw:/app/configuration
      
  lexongw:
    image: elefebvreoncontainers/ocelot.lexon.gateway:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - LexonMySqlUrlHC=http://lexon.mysql.api/hc
      - AccountsUrlHC=http://accounts.api/hc
    ports:
      - "8086:80"   
      
  accountsgw:
    image: elefebvreoncontainers/ocelot.account.gateway:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - LexonMySqlUrlHC=http://lexon.mysql.api/hc
      - AccountsUrlHC=http://accounts.api/hc
    ports:
      - "8083:80"   

#traefik console: 8080 OK
#smtp-imap.client: 8081 
#account.service: 8082 OK
#account.gateway: 8083 OK
#lexon.mysql.service: 8084
#lexon.service: 8085
#lexon.gateway: 8086
#portal.client: 8087
#google.client: 8088
#outlook.client: 8089
#lexon.client: 8090
#rabbitmq console: 15672 
#rabbitmq tcp: 5672



#  Portal-client:
#    image: elefebvreoncontainers/portal.client:latest
#    ports:
#      - "8082:80"      
#    labels:
#      - Lefebvre-Portal-client    
#      
#  Google-client:
#    image: elefebvreoncontainers/google.client:latest
#    ports:
#      - "8083:80"     
#    labels:
#      - Lefebvre-Google-client
#      
#  Office365-client:
#    image: elefebvreoncontainers/office365.client:latest
#    ports:
#      - "8084:80"      
#    labels:
#      - Lefebvre-Office365-client    
#            
#  LexOn-client:
#    image: elefebvreoncontainers/lexon.client:latest
#    ports:
#      - "8085:80"      
#    labels:
#      - Lefebvre-lexon-client            
