version: '3.4'

services:

#  seq:
#    image: datalust/seq:latest

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  # webstatus:
  #   image: ${REGISTRY:-elefebvreoncontainers}/webstatuslef:${PLATFORM:-linux}-${TAG:-dev}
  #   build:
  #     context: .
  #     dockerfile: src/Web/WebStatusLef/Dockerfile
      

  account.api:
    image: ${REGISTRY:-elefebvreoncontainers}/account.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  webaccountapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - account.api
      - lexon.api
      - lexon.mysql.api
      - userutils.api
      - centinela.api

  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq
      - lexon.api

  weblexonapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - account.api
      - lexon.api
      - lexon.mysql.api
      - userutils.api
      - centinela.api
           
  userutils.api:
    image: ${REGISTRY:-elefebvreoncontainers}/userutils.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/UserUtils/UserUtils.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  centinela.api:
    image: ${REGISTRY:-elefebvreoncontainers}/centinela.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Centinela/Centinela.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  webcentinelaapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - centinela.api
      - userutils.api