version: '3'

services:

  reverse-proxy:
    image: traefik:1.7.13
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8086:80"       
      
  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - lexon.mysql.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8087:80"       

  account.api:
    image: ${REGISTRY:-elefebvreoncontainers}/account.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8088:80"      

  lexonapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/lefebvre.gw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - lexon.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - EmailUserUrlHC=http://emailuser.api/hc
    ports:
      - "8089:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Lexon/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}
      
  accountgw:
    image: ${REGISTRY:-elefebvreoncontainers}/lefebvre.gw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - account.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - EmailUserUrlHC=http://emailuser.api/hc
    ports:
      - "8090:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Account/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}      


#  isotope-server:
#    image: elefebvreoncontainers/imapsmtp.client:server-latest
#    ports:
#      - "9010:9010"
#    labels:
#      - traefik.backend=lefebvre-imap-smtp-server
#      - "traefik.frontend.rule=PathPrefixStrip:/api/"
#
#  isotope-client:
#    image: elefebvreoncontainers/imapsmtp.client:client-latest
#    ports:
#      - "8081:80"
#    labels:
#      - traefik.backend=lefebvre-imap-smtp-client
#      - "traefik.frontend.rule=PathPrefixStrip:/"
#      
#  Portal-client:
#    image: elefebvreoncontainers/portal.client:latest
#    ports:
#      - "8082:80"      
#    labels:
#      - Lefebvre-Portal-client    
#      
#  Google-client:
#    image: elefebvreoncontainers/google.client:latest
#    ports:
#      - "8083:80"     
#    labels:
#      - Lefebvre-Google-client
#      
#  Office365-client:
#    image: elefebvreoncontainers/office365.client:latest
#    ports:
#      - "8084:80"      
#    labels:
#      - Lefebvre-Office365-client    
#            
#  LexOn-client:
#    image: elefebvreoncontainers/lexon.client:latest
#    ports:
#      - "8085:80"      
#    labels:
#      - Lefebvre-lexon-client            
