version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  lexon.api:
    image: ${REGISTRY:-paconaf}/lexon.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  emailuser.api:
    image: ${REGISTRY:-paconaf}/emailuser.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/EmailUserAccount/EmailUserAccount.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  lexonapigw:
    image: ${REGISTRY:-paconaf}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - lexon.api

  emailuserapigw:
    image: ${REGISTRY:-paconaf}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Lefebvre/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - emailuser.api

  webstatus:
    image: ${REGISTRY:-paconaf}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile
  