version: '3'

# actualizado con https://github.com/avalverde-lef/Lefebvre-Multichannel/blob/master/docker-compose.yml el 20191024
services:

  reverse-proxy:
    image: traefik:1.7.13
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  imap-server:
    image: avalverdelefebvre/react-imapsmtp-docker:server-latest
    ports:
      - "9010:9010"
    labels:
      - traefik.backend=lefebvre-imap-smtp-server
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  imap-client:
    image: avalverdelefebvre/react-imapsmtp-docker:client-newdesign-latest
    ports:
      - "8081:80"
    labels:
      - traefik.backend=lefebvre-imap-smtp-client
      - "traefik.frontend.rule=PathPrefixStrip:/" 
      
  account-api:
    image: elefebvreoncontainers/account.api:latest
    ports:
      - "8082:80"

  portal-client:
    image: elefebvreoncontainers/portal.client:latest
    ports:
      - "8087:80"  
      
  google-client:
    image: elefebvreoncontainers/google.client:latest
    ports:
      - "8088:80"
      
  lexon-client:
    image: elefebvreoncontainers/lexonconnector.client:latest
    ports:
      - "8090:80"

  lexongw:
    image: elefebvreoncontainers/ocelot.lexon.gateway:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - LexonMySqlUrlHC=http://lexon.mysql.api/hc
      - AccountsUrlHC=http://accounts.api/hc
    ports:
      - "8086:80"
           
  accountsgw:
    image: elefebvreoncontainers/ocelot.account.gateway:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonUrlHC=http://lexon.api/hc
      - LexonMySqlUrlHC=http://lexon.mysql.api/hc
      - AccountsUrlHC=http://accounts.api/hc
    ports:
      - "8083:80" 

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionString="database=lexon_conecta;server=mysqldevlexon.lefebvre.es;port=3315;user id=led-app-conecta-azure;password=FDSk2q3+asd5;sslmode=none"
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8084:80"      
      
  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${TAG:-latest}
    depends_on:
      - lexon.mysql.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - LexonMySqlUrl=https://lefebvre-mysql-service.azurewebsites.net/api/v1/LexonMySql
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8085:80"      

 
#traefik console: 8080 OK
#smtp-imap.client: 8081 
#account.service: 8082 OK
#account.gateway: 8083 OK
#lexon.mysql.service: 8084
#lexon.service: 8085
#lexon.gateway: 8086
#portal.client: 8087
#google.client: 8088
#outlook.client: 8089
#lexon.client: 8090
#rabbitmq console: 15672 
#rabbitmq tcp: 5672
