version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  webstatus:
    image: ${REGISTRY:-elefebvreoncontainers}/webstatuslef:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebStatusLef/Dockerfile
      
  webportalclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webportalclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebPortalClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq

  webgoogleclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webgoogleclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebGoogleClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq

  webofficeclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webofficeclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebOffice365Client/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq
     
  weblexonclient:
    image: ${REGISTRY:-elefebvreoncontainers}/weblexonclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebLexonClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq

  webaddonlauncher:
    image: ${REGISTRY:-elefebvreoncontainers}/webaddonlauncher:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebAddonLauncher/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq

  weboffice365addonlexon:
    image: ${REGISTRY:-elefebvreoncontainers}/weboffice365addonlexon:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Addon/Lexon/Office365/WebOffice365AddonLexon/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq

  weboffice365addoncentinela:
    image: ${REGISTRY:-elefebvreoncontainers}/weboffice365addoncentinela:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Addon/Centinela/Office365/WebOffice365AddonCentinela/Dockerfile    
      args:
       NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq
  
  account.api:
    image: ${REGISTRY:-elefebvreoncontainers}/account.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  webaccountapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - account.api
      - lexon.api
      - lexon.mysql.api
      - userutils.api
      - centinela.api
      - signature.api

  lexon.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  lexon.mysql.api:
    image: ${REGISTRY:-elefebvreoncontainers}/lexon.mysql.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq
      - lexon.api

  weblexonapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - account.api
      - lexon.api
      - lexon.mysql.api
      - userutils.api
      - centinela.api
      
  webimapclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webimapclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebImapClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq   
      
  userutils.api:
    image: ${REGISTRY:-elefebvreoncontainers}/userutils.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/UserUtils/UserUtils.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  centinela.api:
    image: ${REGISTRY:-elefebvreoncontainers}/centinela.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Centinela/Centinela.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  webcentinelaapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - centinela.api
      - userutils.api

  websignatureclient:
    image: ${REGISTRY:-elefebvreoncontainers}/websignatureclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebSignatureClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq   

  webcentinelaclient:
    image: ${REGISTRY:-elefebvreoncontainers}/webcentinelaclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebCentinelaClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq  

  signature.api:
    image: ${REGISTRY:-elefebvreoncontainers}/signature.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Signature/Signature.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  websignatureapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - signature.api

  database.api:
    image: ${REGISTRY:-elefebvreoncontainers}/database.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Database/Database.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  webdatabaseapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - database.api