version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  nosql.data:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  lexon.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZURE_NOSQL_DB}
      - Database=LexonApiDB
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_PASSWORD
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - EventBus__username=${ESHOP_SERVICE_BUS_USERNAME}      
      - EventBus__password=${ESHOP_SERVICE_BUS_PASSWORD}      
      - EventBus__hostname=${ESHOP_SERVICE_BUS_HOSTNAME}      
      - EventBus__virtualhost=${ESHOP_SERVICE_BUS_VIRTUALHOST}      
      - EventBus__port=${ESHOP_SERVICE_BUS_PORT}      
      - EventBus__retrycount=${ESHOP_SERVICE_BUS_RETRYCOUNT}      
      - AzureServiceBusEnabled=False
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST}

    ports:
      - "5301:80"   # Important: In a production environment your should remove the external port (5203) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80). 

  emailuser.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZURE_NOSQL_DB}
      - Database=users-accounts
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_PASSWORD
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - EventBus__username=${ESHOP_SERVICE_BUS_USERNAME}      
      - EventBus__password=${ESHOP_SERVICE_BUS_PASSWORD}      
      - EventBus__hostname=${ESHOP_SERVICE_BUS_HOSTNAME}      
      - EventBus__virtualhost=${ESHOP_SERVICE_BUS_VIRTUALHOST}      
      - EventBus__port=${ESHOP_SERVICE_BUS_PORT}      
      - EventBus__retrycount=${ESHOP_SERVICE_BUS_RETRYCOUNT}      
      - AzureServiceBusEnabled=False
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST}

    ports:
      - "5302:80"   # Important: In a production environment your should remove the external port (5203) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  lexonapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__lexon=http://lexon.api
      - urls__emailuser=http://emailuser.api
      - LexonUrlHC=http://lexon.api/hc
      - EmailUserUrlHC=http://emailuser.api/hc

    ports:
      - "5401:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Lexon/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  emailuserapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__lexon=http://lexon.api
      - urls__emailuser=http://emailuser.api
      - LexonUrlHC=http://lexon.api/hc
      - EmailUserUrlHC=http://emailuser.api/hc
    ports:
      - "5402:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.EmailUser/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Lexon HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://lexon.api/hc
      - HealthChecksUI__HealthChecks__1__Name=Email User HTTP Background Check
      - HealthChecksUI__HealthChecks__1__Uri=http://emailuser/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5107:80"


