version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  weblexonclient:
    image: ${REGISTRY:-elefebvreoncontainers}/weblexonclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebLexonClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq
      
  webofficeaddon:
    image: ${REGISTRY:-elefebvreoncontainers}/webofficeaddon:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Addon/Lexon/Office365/WebOffice365Addon/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq
  
 