{{- $name := include "apigwcen.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "apigwcen.name" . }}
    chart: {{ template "apigwcen.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    env: {{ .Values.lef.env }}
    version: {{ .Chart.Version | quote }} 
data:
  internalurls__identity: http://{{ .Values.app.svc.identity }}
  internalurls__identity__hc: http://{{ .Values.app.svc.identity }}/hc
  internalurls__account__hc: http://{{ .Values.app.svc.accountapi }}/hc
  internalurls__centinela__hc: http://{{ .Values.app.svc.centinelaapi }}/hc
  internalurls__conference__hc: http://{{ .Values.app.svc.conferenceapi }}/hc
  internalurls__lexon__hc: http://{{ .Values.app.svc.lexonapi }}/hc
  internalurls__signature__hc: http://{{ .Values.app.svc.signatureapi }}/hc
  internalurls__userutils__hc: http://{{ .Values.app.svc.userutilsapi }}/hc
  all__Version: {{ .Chart.Version | quote }}

