# This helm values file defines app-based settings
# Charts use those values, so this file **MUST** be included in all chart releases


app:                                                  # app global settings
  name: "my-elef"                                    # Override for custom app name
  ingress:                                            # ingress related settings
    entries:
      identity: identity                              # ingress entry for identity api
      webhooks: webhooks-api                          # ingress entry for webhooks api
      webhooksweb: webhooks-web                       # ingress entry for webhooks web demo client
      status: webstatus                               # ingress entry for web status lef
      portal: webportal                               # ingress entry for webportal client
      google: webgoogle                               # ingress entry for webgoogle client
      graph: webgraph                                 # ingress entry for webgraph client
      lexon: weblexon                                 # ingress entry for weblexon client
      imap: webimap                                   # ingress entry for webimap client
      imapserver: webimapserver                       # ingress entry for webimap server
      signature: websignature                         # ingress entry for websignature client      
      accountapigw: accountapigw                      # ingress entry for account api gw 
      accountapi: account-api                         # ingress entry for account api
      lexonapigw: lexonapigw                          # ingress entry for lexon api gw
      lexonapi: lexon-api                             # ingress entry for lexon api
      lexonmysqlapi: lexonmysql-api                   # ingress entry for lexon mysql api
      centinelaapigw: centinelaapigw                  # ingress entry for centinela api gw
      centinelaapi: centinela-api                     # ingress entry for centinela api
      userutilsapi: userutils-api                     # ingress entry for userutils api
      signatureapigw: signatureapigw                  # ingress entry for signature api gw
      signatureapi: signature-api                     # ingress entry for signature api      
      addonlexon: webaddonlexon
      
  svc:
      identity: identity                              # svc entry for identity api
      webhooks: webhooks-api                          # svc entry for webhooks api
      webhooksweb: webhooks-web                       # svc entry for webhooks web demo client
      status: webstatus                               # svc entry for web status
      portal: webportal                               # svc entry for webportal client
      google: webgoogle                               # svc entry for webgoogle client
      graph: webgraph                                 # svc entry for webgraph client
      lexon: weblexon                                 # svc entry for weblexon client
      imap: webimap                                   # svc entry for webimap client
      imapserver: webimapserver                       # svc entry for webimap server
      signature: websignature                         # svc entry for websignature client
      accountapigw: accountapigw                      # svc entry for marketing api
      accountapi: account-api                         # svc entry for marketing api
      lexonapigw: lexonapigw                          # svc entry for marketing api
      lexonapi: lexon-api                             # svc entry for lexon api
      lexonmysqlapi: lexonmysql-api                   # svc entry for lexon mysql api
      centinelaapigw: centinelaapigw                  # ingress entry for centinela api gw
      centinelaapi: centinela-api                     # ingress entry for centinela api
      userutilsapi: userutils-api                     # ingress entry for userutils api
      signatureapigw: signatureapigw                  # svc entry for signature api gw
      signatureapi: signature-api                     # svc entry for signature api
      addonlexon: webaddonlexon
