apiVersion: v1
version: 0.37.0
name: conference-api
description: Conference management API via jitsi
home: https://github.com/lefevbre-organization/eShopOnContainers
icon: https://github.com/lefevbre-organization/eShopOnContainers/blob/lef-main-containers/img/eshop_logo.png
keywords: ["jitsi", "conference", "service", "infrastructure"]
sources:
  - https://github.com/lefevbre-organization/eShopOnContainers/tree/lef-main-containers/src/Services/Conference/Conference.API

