apiVersion: v1
name: lexon-api
version: 0.41
description: Lexon management API
home: https://github.com/lefevbre-organization/eShopOnContainers
icon: https://github.com/lefevbre-organization/eShopOnContainers/blob/lef-main-containers/img/eshop_logo.png
keywords: ["lawyer", "managment", "service", "infrastructure"]
sources:
  - https://github.com/lefevbre-organization/eShopOnContainers/tree/lef-main-containers/src/Services/Lexon/Lexon.API
