export const PAGE_LOGIN = "PAGE_LOGIN";
export const PAGE_SELECT_COMPANY = "PAGE_SELECT_COMPANY";
export const PAGE_MESSAGE_CLASSIFICATIONS = "PAGE_MESSAGE_CLASSIFICATIONS";
export const PAGE_DOCUMENT_ATTACHED = "PAGE_DOCUMENT_ATTACHED";
