replicaCount: 1
clusterName: eshop-aks
pathBase: /centinelaapigw

image:
  repository: elefebvreoncontainers/ocelotapigw
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: IdentityUrl
      key: internalurls__identity
    - name: IdentityUrlHC
      key: internalurls__identity__hc
    - name: AccountApiUrlHC
      key: internalurls__accountapi__hc
    - name: CentinelaApiUrlHC
      key: internalurls__centinelaapi__hc
    - name: ConferenceApiUrlHC
      key: internalurls__conferenceapi__hc
    - name: LexonApiUrlHC
      key: internalurls__lexonapi__hc
    - name: SignatureApiUrlHC
      key: internalurls__signatureapi__hc
    - name: UserUtilsApiUrlHC
      key: internalurls__userutilsapi__hc
    - name: DeployVersion
      key: all__Version
  # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
#  values: {}

ocelot:
  configPath: /app/configuration
