replicaCount: 1
clusterName: eshop-aks
pathBase: /centinelaapigw

image:
  repository: elefebvreoncontainers/ocelotapigw
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: IdentityUrl
      key: internalurls__identity
    - name: LexonUrlHC
      key: internalurls__lexonapi__hc
    - name: LexonMySqlUrlHC
      key: internalurls__lexonmysqlapi__hc
    - name: AccountsUrlHC
      key: internalurls__accountapi__hc
    - name: CentinelaUrlHC
      key: internalurls__centinelaapi__hc
    - name: UserUtilsUrlHC
      key: internalurls__userutils__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

ocelot:
  configPath: /app/configuration
