replicaCount: 1
clusterName: eshop-aks
pathBase: /webimap

image:
  repository: elefebvreoncontainers/webimapclient
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: UseLoadTest
      key: all_EnableLoadTest
    - name: AccountApiUrlHC
      key: internalurls__accountapi__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
configValues: |
  window.REACT_APP_ENVIRONMENT='PRODUCTION'
  window.URL_UPDATE_DEFAULTACCOUNT='https://lexbox-apigwacc.lefebvre.es/api/v1/accounts/emailuseraccount/updatedefaultaccount'
  window.URL_RESET_DEFAULTACCOUNT='https://lexbox-apigwacc.lefebvre.es/api/v1/accounts/emailuseraccount/resetdefaultaccountbyuser'
  window.URL_DELETE_ACCOUNT='https://lexbox-apigwacc.lefebvre.es/api/v1/accounts/emailuseraccount/deleteaccountbyuserandprovider'
  window.URL_SELECT_ACCOUNT='https://lexbox.lefebvre.es'
  window.URL_GET_ACCOUNTS='https://lexbox-apigwacc.lefebvre.es/api/v2/accounts/usermail'
  window.URL_MF_GOOGLE='https://lexbox-webgoogle.lefebvre.es/user'
  window.URL_MF_OUTLOOK='https://lexbox-webgraph.lefebvre.es/user'
  window.URL_MF_IMAP='https://lexbox-webimap.lefebvre.es/user'
  window.URL_MF_LEXON='https://lexbox-weblexon.lefebvre.es/static/js/main.js'
  window.API_GATEWAY='https://lexbox-apigwlex.lefebvre.es' 
  window.API_ACC_GATEWAY = 'https://lexbox-apigwacc.lefebvre.es' 
  window.URL_MF_LEXON_BASE = 'https://lexbox-weblexon.lefebvre.es' 
  window.URL_MF_CENTINELA_BASE = 'https://lexbox-webcentinela.lefebvre.es'
  window.URL_MF_CENTINELA = 'https://lexbox-webcentinela.lefebvre.es/static/js/main.js'
  window.API_CENTINELA_GATEWAY =   'https://lexbox-apigwcen.lefebvre.es/api/v1/cen'
  window.URL_MF_DATABASE='http://localhost:3006/static/js/main.js'
  window.URL_MF_DATABASE_BASE='http://localhost:3006'
  window.NEXTCLOUD_URL = 'https://lexbox-dev-nextcloud.lefebvre.es';
  window.NEXTCOUD_ADMIN_USERNAME = 'admin';
  window.NEXTCLOUD_ADMIN_PASSWD = 'admin_dev';
  window.NEXTCLOUD_USERS_PASSWD = 'users_passwd';
  window.SHOW_EXPERIMENTAL='0'  
  window.RELEASE= 'RC 0.42'
