{{- $name := include "websignature.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "websignature.name" . }}
    chart: {{ template "websignature.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  all__EnableLoadTest: "{{ .Values.inf.misc.useLoadTest }}"
  all__version: "RC {{ .Values.inf.version.major }}.{{ .Values.inf.version.minor }}"
  internalurls__signature__hc: http://{{ .Values.app.svc.signatureapi }}/hc
  config.js: {{ toYaml .Values.configValues | indent 4 }}
