apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "mariadb"  }}
  namespace: default
  labels:
    app: "mariadb"
    chart: "mariadb-7.10.2"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mariadb-root-password: "NVlybThVQm9weQ==" 
  mariadb-password: "ZWxlZmVidnJlXzEyMzQ="