lef:
  env: 'pro'

centinela:
  user: 'CentinelaAPI'
  pass: 'muWeEtF3ht#9yJPB'
  url: 'centinela-api.lefebvre.es/api/secure'

lexon:
  devs:
    env: 'DEVS'
    conn: 'database=lexondevconecta;server=10.38.6.22;port=3315;user id=led-app-conecta-aws;password=FDSk2q3+asd5;Connect Timeout=90'
    url: 'led-dev-lexon.eu.els.local'
  dev:
    env: 'DEV'
    conn: 'database=lexon_conecta;server=10.38.6.22;port=3315;user id=led-app-conecta-aws;password=FDSk2q3+asd5;Connect Timeout=90'
    url: 'led-dev-lexon.eu.els.local'
  qa:
    env: 'QA'
    conn: 'database=lexon_qa_conecta;server=10.38.6.22;port=3315;user id=led-app-conecta-aws;password=FDSk2q3+asd5;Connect Timeout=90'
    url: 'www-led-pre.lex-on.es'
  pre:
    env: 'PRE'
    conn: 'database=lexon_pre_conecta;server=10.38.6.22;port=3315;user id=led-app-conecta-aws;password=FDSk2q3+asd5;Connect Timeout=90'
    url: 'www-led-pre.lex-on.es'
  pro:
    env: 'PRO'
    conn: 'database=lexon_conecta;server=192.168.71.11;port=3308;user id=led-app-conecta-aws;password=Fgo23+gap4FB;Connection Timeout=100'
    url: 'www.lex-on.es'      

signature:
  url: 'api.signaturit.com/v3' # name: SignaturitApiUrl
  pass: 'rRSMTouEvOtQsisUtwpiKBSxVxemmfNCMqUIqvzzwzVsxZsYXxIkyzKOWLgCJhSsBwTgiaNWklPFVtcGBTEEDq'   # name: Signaturit
  lex_url: 'https://led-lexon.eu.els.local' #name : LexonFilesUrl
  callbackurl: 'lexbox-websignature.lefebvre.es'   # name: CallBackUrl
  paths:
    mail: '/SignaturitEvent/signature/post.json'   # name: SignatureNotificationUrl
    certified_mail: '/SignaturitEvent/certifiedEmail/post.json'   # name: CertifiedEmailNotificationUrl
    certified_sms: '/SignaturitEvent/certifiedSms/post.json'   # name: CertifiedSmsNotificationUrl

svchub:
  url: 'led-servicehub.eu.els.local' # name: MinihubUrl

svconline:
  url: 'https://online.elderecho.com/ws' # name: OnlineUrl
  login: 'ws'
  pass: '22lcqsp11lsw'

svccomtools:
  url: 'led-servicecomtools_ntt.eu.els.local' # name: LoginUrl
  
svcclaves:
  url: 'led-serviceclaves.lefebvre.es' # name: ClavesUrl  

userutils:
  token:
    caducity: 1500
    key: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9'
  bypass:
    lex:
      id: 'Lex-On'
      url: 'lexbox-apigwlex.lefebvre.es/api/v1/utils/UserUtils/user/apps/redirect?NameService={serviceName}&idUser={idUserNavision}'
    sig:
      id: 'Signature-Direct'
      url: 'lexbox-websignature.lefebvre.es/access/{tokenSignature}'


env:
  values:
    - name: ASPNETCORE_ENVIRONMENT # selector of appsettings by default
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: DefaultEnvironment #use if not include de env variable in the internal and external requests
      value: 'PRO'
    - name: UseMongo  # if set to true, use de mongo to admi use without external 
      value: false
    - name: Environments # list of environments admit in the cluster
      value: ['PRO']
    - name: IsClusterEnv
      value: 'True'
    - name: EvaluationTimeOnSeconds
      value: 90
    - name: MinimumSecondsBetweenFailureNotifications
      value: 90