variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Web/WebStatuslef/*
    - k8s-LEF/helm/webstatuslef/* 
jobs:
- template: ../buildimages.yaml
  parameters:
    services: webstatus
    registryEndpoint: $(registryEndpoint)         
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm          
