variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Web/WebStatus/*
    - k8s-LEF/helm/webstatus/* 
jobs:
- template: ../buildimages.yaml
  parameters:
    services: webstatuslef
    registryEndpoint: $(registryEndpoint)         
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm          
- template: ../multiarch.yaml
  parameters:
    image: webstatuslef
    branch: $(Build.SourceBranchName)
    registryEndpoint: $(registryEndpoint)