apiVersion: v1
kind: ConfigMap
metadata:
  name: webportalclient-config
data:
  config.js: |
    window.REACT_APP_ENVIRONMENT='DEV'
    window.API_ACCOUNTS='http://localhost:8083'
    window.URL_INBOX_GOOGLE= 'http://localhost:3000'
    window.URL_INBOX_OUTLOOK= 'http://localhost:3001'
    window.URL_INBOX_IMAP= 'http://localhost:3005'

