FROM nginx:1.15.2-alpine

MAINTAINER Alberto Valverde <a.valverde-ext@lefebvreelderecho.com>
LABEL MAINTAINER Alberto Valverde <a.valverde-ext@lefebvreelderecho.com>

COPY ./client/dist/imap_client.pem /etc/nginx/conf.d/imap_client.pem
COPY ./client/dist/imap_client_key.pem /etc/nginx/conf.d/imap_client_key.pem
COPY ./client/dist/imap_client_key_pass.txt /etc/nginx/conf.d/imap_client_key_pass.txt
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./client/dist /usr/share/nginx/html
RUN ls -lha /etc/nginx/conf.d
EXPOSE 80
EXPOSE 443
CMD nginx -g 'daemon off;'

