FROM openjdk:8-jre-alpine

MAINTAINER Alberto Vavlerde <a.valverde-ext@lefebvreelderecho.com>
LABEL MAINTAINER "Alberto Valverde" <a.valverde-ext@lefebvreelderecho.com>

EXPOSE 9010

COPY ./server/build/libs /opt

CMD java -jar /opt/api-0.0.1-SNAPSHOT.jar
