FROM nginx:1.15.2-alpine

MAINTAINER Alberto Valverde <a.valverde-ext@lefebvreelderecho.com>
LABEL MAINTAINER Alberto Valverde <a.valverde-ext@lefebvreelderecho.com>

EXPOSE 80

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./client/dist /usr/share/nginx/html

CMD nginx -g 'daemon off;'
