---
# Source: seq/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-elefebvre-seq
  labels:
    app: seq
    chart: seq-2020.4.5070
    release: it-elefebvre-seq
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: seq
      release: it-elefebvre-seq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seq
        release: it-elefebvre-seq
    spec:
      containers:
        - name: seq
          image: "datalust/seq:2020.4.5070"
          imagePullPolicy: IfNotPresent
          env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "SEQ_CACHE_SYSTEMRAMTARGET"
              value: "0.7"
          ports:
            - name: ingestion
              containerPort: 5341
              protocol: TCP
            - name: ui
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ui
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: ui
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /
              port: ui
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
          - name: seq-data
            mountPath: /data
            subPath: 
          resources:
            {}
      serviceAccountName: "default"
      volumes:
      - name: seq-data
        persistentVolumeClaim:
          claimName: it-elefebvre-seq

