# Source: seq/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: it-elefebvre-seq
  labels:
    app: seq
    chart: seq-2020.4.5070
    release: it-elefebvre-seq
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ui
      protocol: TCP
      name: ui
    - port: 5341
      targetPort: ingestion
      protocol: TCP
      name: ingestion
  selector:
    app: seq
    release: it-elefebvre-seq