replicaCount: 1
clusterName: eshop-aks
pathBase: /websignature

image:
  repository: elefebvreoncontainers/websignatureclient
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: UseLoadTest
      key: all_EnableLoadTest
    - name: SignatureApiUrlHC
      key: internalurls__signatureapi__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
configValues: |
  window.REACT_APP_ENVIRONMENT = 'PRODUCTION'
  window.API_SIGN_GATEWAY = 'https://lexbox-apigwsig.lefebvre.es/api/v1/signservice'
  window.API_UTILS_GATEWAY = 'https://lexbox-apigwsig.lefebvre.es/api/v1/utils'
  window.TERMS_AND_CONDITIONS_URL = 'https://lefebvre.es/aviso-legal'
  window.COOKIES_POLICY_URL = 'https://lefebvre.es/politica-cookies'
  window.PRIVACY_POLICY_URL = 'https://lefebvre.es/politica-privacidad'
  window.LEGAL_WARNING_URL = 'https://lefebvre.es/aviso-legal'
  window.URL_GET_ACCOUNTS = 'https://lexbox-apigwacc.lefebvre.es/api/v2/accounts/usermail'
  window.URL_GET_USER = 'https://lexbox-apigwlex.lefebvre.es/api/v1/utils/UserUtils/user/login'
  window.POLLING_INTERVAL = 45000
  window.RELEASE = 'RC 0.29'