replicaCount: 1
clusterName: eshop-aks
pathBase: /webaddonlauncher

image:
  repository: elefebvreoncontainers/webaddonlauncher
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: UseLoadTest
      key: all_EnableLoadTest
    - name: LexonApiGatewayUrlHC
      key: internalurls__lexonapigw__hc
    - name: AccountApiGatewayUrlHC
      key: internalurls__accountapigw__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
configValues: |
 window.REACT_APP_ENVIRONMENT='PRODUCTION'
 window.GOOGLE_SCRIPT='https://script.google.com/macros/d/17OVCKEejIyIITkMSVlF3KJelJFI1ouLFeoS2Wj4sO7U4hlS1URiK_Ntk/usercallback'
 window.API_GATEWAY='https://lexbox-test-apigwlex.lefebvre.es'
 window.URL_MF_LEXON='https://lexbox-test-weblexon.lefebvre.es/static/js/main.js'
 window.URL_GET_ACCOUNTS='https://lexbox-test-apigwacc.lefebvre.es/api/v2/accounts/usermail'
 window.URL_MF_LEXON_BASE='https://lexbox-test-weblexon.lefebvre.es'
 window.URL_GET_USER='https://lexbox-test-apigwlex.lefebvre.es/api/v1/utils/UserUtils'
 window.RELEASE = 'RC 0.26'
