{{- if .Values.ingress.enabled -}}
{{- $ingressPath := include "pathBase" . -}}
{{- $serviceName := .Values.app.svc.conferenceapi }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "conference-api.fullname" . }}
  labels:
    app: {{ template "conference-api.name" . }}
    chart: {{ template "conference-api.chart" . }}
    heritage: {{ .Release.Service }}
    env: {{ .Values.lef.env }}
    version: {{ .Chart.Version | quote }} 
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
        - {{ .Values.inf.k8s.dns }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: http
  {{- end }}
{{- end }}
