variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - lef-main-containers
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Web/WebPortalClient/*
    - deploy/k8s-lef/helm/webportal/*            
jobs:
- template: ../buildimages.yaml
  parameters:
    services: webportalclient
    registryEndpoint: $(registryEndpoint)          
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm      
