apiVersion: v1
name: websignature
description: signature client for mail   
home: https://github.com/lefevbre-organization/eShopOnContainers
icon: https://github.com/lefevbre-organization/eShopOnContainers/blob/lef-main-containers/img/eshop_logo.png
keywords: ["signature", "webclient", "security"]
version: 0.39
sources:
  - https://github.com/lefevbre-organization/eShopOnContainers/tree/lef-main-containers/src/web/WebSignatureClient
