FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src

COPY ["BuildingBlocks/EventBus/EventBus/EventBus.csproj", "src/BuildingBlocks/EventBus/EventBus/"]
COPY ["BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj", "src/BuildingBlocks/EventBus/EventBusRabbitMQ/"]
COPY ["BuildingBlocks/EventBus/IntegrationEventLogMongoDB/IntegrationEventLogMongoDB.csproj", "src/BuildingBlocks/EventBus/IntegrationEventLogMongoDB/"]
COPY ["Services/Lexon/Lexon.MySql/Lexon.MySql.csproj", Services/Lexon/Lexon.MySql/"]

RUN dotnet restore Services/Lexon/Lexon.MySql/Lexon.MySql.csproj -nowarn:msb3202,nu1503
COPY . .
WORKDIR "/src/Services/Lexon/Lexon.API"
RUN dotnet build  --no-restore -c $BUILD_CONFIGURATION
ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]