variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - lef-main-containers
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Services/Google/GoogleAccount.API/*
    - deploy/k8s-lef/helm/googleaccount-api/*
jobs:
- template: ../buildimages.yaml
  parameters:
    services: googleaccount.api
    registryEndpoint: $(registryEndpoint)
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm    

