apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: it-elefebvre-nextcloud
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-03-01T18:34:41Z"
  generation: 1
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: it-elefebvre-nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nextcloud
    env: dev
    helm.sh/chart: nextcloud-2.5.1
    version: 2.5.1
  name: it-elefebvre-nextcloud
  namespace: default
  resourceVersion: "36382227"
  selfLink: /apis/apps/v1/namespaces/default/deployments/it-elefebvre-nextcloud
  uid: 1c3ebbe6-2684-4aab-9fb0-a2d21a8017f1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: it-elefebvre-nextcloud
      app.kubernetes.io/name: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: it-elefebvre-nextcloud
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: it-elefebvre-nextcloud-mariadb
        - name: MYSQL_DATABASE
          value: nextcloud_dev
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: nextcloud-secrets
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: nextcloud-secrets
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: nextcloud-secrets
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: nextcloud-secrets
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: lexbox-dev-nextcloud.lefebvre.es
        - name: NEXTCLOUD_DATA_DIR
          value: /var/www/html/data
        image: elefebvreoncontainers/nextcloud:linux-dev-40.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: lexbox-dev-nextcloud.lefebvre.es
            path: /status.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: nextcloud
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: lexbox-dev-nextcloud.lefebvre.es
            path: /status.php
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/
          name: nextcloud-data
          subPath: root
        - mountPath: /var/www/html
          name: nextcloud-data
          subPath: html
        - mountPath: /var/www/html/data
          name: nextcloud-data
          subPath: data
        - mountPath: /var/www/html/config
          name: nextcloud-data
          subPath: config
        - mountPath: /var/www/html/custom_apps
          name: nextcloud-data
          subPath: custom_apps
        - mountPath: /var/www/tmp
          name: nextcloud-data
          subPath: tmp
        - mountPath: /var/www/html/themes
          name: nextcloud-data
          subPath: themes
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: elefebvre-docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: elefebvre-vol-nextcloud-server-claim
status:
  conditions:
  - lastTransitionTime: "2021-03-01T18:34:41Z"
    lastUpdateTime: "2021-03-01T18:34:41Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-03-01T18:44:42Z"
    lastUpdateTime: "2021-03-01T18:44:42Z"
    message: ReplicaSet "it-elefebvre-nextcloud-64744c9ccc" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
