apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-nextcloud-mdb
  selfLink: /api/v1/persistentvolumes/pv-nextcloud-mdb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-5e0e5bef
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: elefebvre-vol-nextcloud-mdb-claim
  namespace: default
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/elefebvre-vol-nextcloud-mdb-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: pv-nextcloud-mdb
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
