variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Web/WebSignatureClient/*
    - k8s-LEF/helm/websignature/*            
jobs:
- template: ../buildimages.yaml
  parameters:
    services: websignatureclient
    registryEndpoint: $(registryEndpoint)          
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm      
