replicaCount: 1
clusterName: eshop-aks
pathBase: /signature-api

image:
  repository: elefebvreoncontainers/signature.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - chart-example.local
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: EventBusConnection
      key: all__EventBusConnection
    - name: AzureServiceBusEnabled
      key: all__UseAzureServiceBus
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: IdentityUrlExternal
      key: urls__IdentityUrlExternal
    - name: ConnectionString
      key: signature__ConnectionString
    - name: Database
      key: signature__Database
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: SignaturitApiUrl
      value: 'https://api.signaturit.com/v3'
    - name: LexonFilesUrl
      value: 'https://led-dev-lexon.eu.els.local/index.php'
    - name: LexonApiGwUrl
      value: 'https://lexbox-apigwlex.lefebvre.es/api/v1'
    - name: CentinelaApiGwUrl
      value: 'https://lexbox-apigwcen.lefebvre.es/api/v1/cen'
    - name: CallBackUrl
      value: 'https://lexbox-websignature.lefebvre.es/completed'
    - name: Signaturit
      value: 'rRSMTouEvOtQsisUtwpiKBSxVxemmfNCMqUIqvzzwzVsxZsYXxIkyzKOWLgCJhSsBwTgiaNWklPFVtcGBTEEDq'
    - name: SignatureNotificationUrl
      value: 'https://lexbox-apigwsig.lefebvre.es/api/v1/signservice/SignaturitEvent/signature/post.json'
    - name: CertifiedEmailNotificationUrl
      value: 'https://lexbox-apigwsig.lefebvre.es/api/v1/signservice/SignaturitEvent/certifiedEmail/post.json'      