apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lexon
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: lexon
    spec:
      containers:
      - name: lexon
        image: elefebvre/lexon.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /lexon-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: lexon__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lexonmysql
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: lexonmysql
    spec:
      containers:
      - name: lexon
        image: elefebvre/lexonmysql.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /lexon-mysql-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: lexonmysql__ConnectionString
        - name: PicBaseUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: PicBaseUrl
        - name: AzureStorageEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: catalog__AzureStorageEnabled
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: OrchestratorType
          value: 'K8S' 
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: accounts
    spec:
      containers:
      - name: ordering
        image: elefebvre/accounts.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /accounts-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: accounts__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        - name: CheckUpdateTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager__CheckUpdateTime
        - name: GracePeriodTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager__GracePeriodTime  
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'           
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: payment
    spec:
      containers:
      - name: payment
        image: eshop/payment.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /payment-api
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: OrchestratorType
          value: 'K8S'
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key      
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webstatus
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: webstatus
    spec:
      containers:
      - name: webstatus
        image: eshop/webstatus
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webstatus
        - name: BasketUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: basket__hc
        - name: CatalogUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: catalog__hc
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: identity__hc
        - name: OrderingUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: ordering__hc
        - name: OrderingBackgroundTasksUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: ordering-background__hc
        - name: LocationsUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: locations__hc
        - name: MarketingUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: marketing__hc
        - name: mvc
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: mvc__hc
        - name: spa
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: spa__hc
        - name: PaymentUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: payment__hc 
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey  
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
