kubectl apply -f .\nodeports\rabbitmq-admin.yaml
kubectl apply -f .\nodeports\sql-services.yaml
kubectl apply -f .\nodeports\nosql-services.yaml
kubectl apply -f .\nodeports\account-api.yaml
kubectl apply -f .\nodeports\lexon-api.yaml
kubectl apply -f .\nodeports\centinela-api.yaml
kubectl apply -f .\nodeports\userutils-api.yaml
kubectl apply -f .\nodeports\lexon-mysql-api.yaml
kubectl apply -f .\nodeports\apigwacc.yaml
kubectl apply -f .\nodeports\apigwlex.yaml
kubectl apply -f .\nodeports\apigwcen.yaml
kubectl apply -f .\nodeports\webgraph.yaml
kubectl apply -f .\nodeports\weblexon.yaml
kubectl apply -f .\nodeports\webaddonlexon.yaml
kubectl apply -f .\nodeports\webgoogle.yaml
kubectl apply -f .\nodeports\webimap.yaml
kubectl apply -f .\nodeports\webportal.yaml
