kubectl apply -f .\nodeports\account-api.yaml
kubectl apply -f .\nodeports\calendar-api.yaml
kubectl apply -f .\nodeports\apigwacc.yaml
kubectl apply -f .\nodeports\apigwcen.yaml
kubectl apply -f .\nodeports\apigwlex.yaml
kubectl apply -f .\nodeports\apigwsig.yaml
kubectl apply -f .\nodeports\centinela-api.yaml
kubectl apply -f .\nodeports\lexon-api.yaml
kubectl apply -f .\nodeports\lexon-mysql-api.yaml
kubectl apply -f .\nodeports\nosql-service.yaml
kubectl apply -f .\nodeports\rabbitmq-admin.yaml
kubectl apply -f .\nodeports\signature-api.yaml
kubectl apply -f .\nodeports\sql-service.yaml
kubectl apply -f .\nodeports\userutils-api.yaml
kubectl apply -f .\nodeports\webaddonlexon.yaml
kubectl apply -f .\nodeports\webgoogle.yaml
kubectl apply -f .\nodeports\webgraph.yaml
kubectl apply -f .\nodeports\webimap.yaml
kubectl apply -f .\nodeports\weblexon.yaml
kubectl apply -f .\nodeports\webportal.yaml
kubectl apply -f .\nodeports\websignature.yaml
