apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lexon
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: lexon
    spec:
      containers:
      - name: lexon
        image: elefebvre/lexon.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /lexon-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: lexon__ConnectionString
        - name: LexonMySqlUrl
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: lexon__LexonMySqlUrl
        - name: LexonFilesUrl
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: lexon__LexonFilesUrl
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: EventBusUserName
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusUserName
        - name: EventBusPassword
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusPassword
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lexonmysql
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: lexonmysql
    spec:
      containers:
      - name: lexon
        image: elefebvre/lexonmysql.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /lexon-mysql-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: lexonmysql__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: EventBusUserName
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusUserName
        - name: EventBusPassword
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusPassword
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: accounts
    spec:
      containers:
      - name: ordering
        image: elefebvre/accounts.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /accounts-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: accounts__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: EventBusUserName
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusUserName
        - name: EventBusPassword
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusPassword
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'           
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webportalclient
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: webportalclient
    spec:
      containers:
      - name: webportalclient
        image: elefebvre/webportalclient
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /
        - name: LexonApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexon
        - name: LexonMySqlApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexonmysql
        - name: LexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwlex     
        - name: ExternalLexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwlex_e
        - name: AccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwacc     
        - name: ExternalAccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwacc_e          
        - name: AccountApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: account 
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webgoogleclient
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: webgoogleclient
    spec:
      containers:
      - name: webgoogleclient
        image: elefebvre/webgoogleclient
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webgoogleclient
        - name: LexonApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexon
        - name: LexonMySqlApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexonmysql
        - name: LexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwlex     
        - name: ExternalLexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwlex_e
        - name: AccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwacc     
        - name: ExternalAccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwacc_e          
        - name: AccountApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: account 
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webofficeclient
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: webofficeclient
    spec:
      containers:
      - name: webofficeclient
        image: elefebvre/webofficeclient
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webofficeclient
        - name: LexonApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexon
        - name: LexonMySqlApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexonmysql
        - name: LexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwlex     
        - name: ExternalLexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwlex_e
        - name: AccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwacc     
        - name: ExternalAccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwacc_e          
        - name: AccountApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: account 
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weblexonclient
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: weblexonclient
    spec:
      containers:
      - name: weblexonclient
        image: elefebvre/weblexonclient
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /weblexonclient
        - name: LexonApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexon
        - name: LexonMySqlApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexonmysql
        - name: LexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwlex     
        - name: ExternalLexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwlex_e
        - name: AccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwacc     
        - name: ExternalAccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwacc_e          
        - name: AccountApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: account 
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webloginaddonlexon
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: webloginaddonlexon
    spec:
      containers:
      - name: webloginaddonlexon
        image: elefebvre/webloginaddonlexon
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webloginaddonlexon
        - name: LexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwlex     
        - name: ExternalLexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwlex_e
        - name: AccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwacc     
        - name: ExternalAccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwacc_e      
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webimapclient
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: webimapclient
    spec:
      containers:
      - name: webimapclient
        image: elefebvre/webimapclient
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webimapclient
        - name: LexonApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexon
        - name: LexonMySqlApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexonmysql
        - name: LexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: apigwlex     
        - name: ExternalLexonApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: apigwlex_e
        - name: AccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: webaccountapigw     
        - name: ExternalAccountApiGatewayUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: webaccountapigw_e          
        - name: AccountApiUrlHC
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: account 
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webstatus
spec:
  paused: true
  template:
    metadata:
      labels:
        app: elefebvre
        component: webstatus
    spec:
      containers:
      - name: webstatus
        image: elefebvre/webstatus
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webstatus
        - name: WebpPortalClient
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: webportalclient__hc
        - name: WebGoogleClient
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: webgoogleclient__hc
        - name: WebOfficeClient
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: webofficeclient__hc
        - name: WebImapClient
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: webimapclient__hc
        - name: WebLexonClient
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: weblexonclient__hc
        - name: AccountApi
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: account__hc
        - name: LexonApi
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexon__hc
        - name: LexonMysqlApi
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: lexonmysql__hc
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__InstrumentationKey  
        - name: OrchestratorType
          value: 'K8S'       
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
