apiVersion: v1
kind: ConfigMap
metadata:
  name: internalurls
  labels:
    app: eshop  
data:
# Internal Services & healthchecks
  lexon: http://lexon.api
  lexon__hc: http://lexon.api/hc
  lexonmysql: http://lexon.mysql.api
  lexonmysql__hc: http://lexon.mysql.api/hc
  account: http://account.api
  account__hc: http://account.api/hc
# Aggreggators
  mobileshoppingagg: http://mobileshoppingagg
  webshoppingagg: http://webshoppingagg
# API GWs
  apigwmm: http://ocelotapigw-mm
  apigwms: http://ocelotapigw-ms
  apigwwm: http://ocelotapigw-wm
  apigwws: http://ocelotapigw-ws