kubectl apply -f .\traefik\accountapigw-traefik-rules.yaml
kubectl apply -f .\traefik\centinelaapigw-traefik-rules.yaml
kubectl apply -f .\traefik\elefebvre-rabbitmq-cluster-persistente.yaml
kubectl apply -f .\traefik\lexonapigw-traefik-rules.yaml
kubectl apply -f .\traefik\signatureapigw-traefik-rules.yaml
kubectl apply -f .\traefik\webgoogle-traefik-rules.yaml
kubectl apply -f .\traefik\webgraph-traefik-rules.yaml
kubectl apply -f .\traefik\webimap-traefik-rules.yaml
kubectl apply -f .\traefik\weblexon-traefik-rules.yaml
kubectl apply -f .\traefik\webportal-traefik-rules.yaml
kubectl apply -f .\traefik\websignature-traefik-rules.yaml
