{{- $name := include "apigwacc.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "apigwacc.name" . }}
    chart: {{ template "apigwacc.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  internalurls__identity: http://{{ .Values.app.svc.identity }}
  internalurls__identity__hc: http://{{ .Values.app.svc.identity }}/hc
  internalurls__account__hc: http://{{ .Values.app.svc.account }}/hc
  internalurls__lexon__hc: http://{{ .Values.app.svc.lexon }}/hc
  internalurls__lexonmysql__hc: http://{{ .Values.app.svc.lexonmysql }}/hc

