using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

//namespace Signature.API.Model
//{
//    [BsonIgnoreExtraElements]
//    public class UserSignatures// : MongoModel
//    {
//        [BsonId]
//        [BsonIgnoreIfDefault]
//        [BsonRepresentation(BsonType.ObjectId)]
//        public string Id { get; set; }

//        /// <summary>
//        /// entrada de usuario en el formato Exxxxxxx para poder operar y comprobar los permisos del usuario
//        /// </summary>
//        [BsonElement("user")]
//        public string User { get; set; }

//        //[BsonElement("office")]
//        //public string Office { get; set; }

//        [BsonElement("availableSignatures")]
//        public int availableSignatures { get; set; }

//        public List<UserBranding> brandings { get; set; }

//        public List<Signature> signatures { get; set; }
//    }
//}


// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Signature.API.Model;
//
//    var userSignatures = UserSignatures.FromJson(jsonString);

namespace Signature.API.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UserSignatures
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("user")]
        public string User { get; set; }

        [JsonProperty("availableSignatures")]
        public int AvailableSignatures { get; set; }

        [JsonProperty("brandings")]
        public List<UserBranding> Brandings { get; set; }

        [JsonProperty("signatures")]
        public List<Signature> Signatures { get; set; }
    }

    public partial class AvailableSignatures
    {
        [JsonProperty("$numberInt")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long NumberInt { get; set; }
    }

    public partial class Branding
    {
        [JsonProperty("app")]
        public string App { get; set; }

        [JsonProperty("externalId")]
        public Guid ExternalId { get; set; }
    }

    public partial class Id
    {
        [JsonProperty("$oid")]
        public string Oid { get; set; }
    }

    public partial class Signature
    {
        [JsonProperty("externalId")]
        public string ExternalId { get; set; }

        [JsonProperty("guid")]
        public string Guid { get; set; }

        [JsonProperty("app")]
        public string App { get; set; }

        [JsonProperty("documents")]
        public List<Document> Documents { get; set; }
    }

    public partial class Document
    {
        [JsonProperty("externalFileName")]
        public string ExternalFileName { get; set; }

        [JsonProperty("externalId")]
        public Guid ExternalId { get; set; }

        [JsonProperty("internalInfo")]
        public InternalInfo InternalInfo { get; set; }

        [JsonProperty("signer")]
        public Signer Signer { get; set; }
    }

    public partial class InternalInfo
    {
        [JsonProperty("docId")]
        public long Id { get; set; }

        [JsonProperty("docName")]
        public string FileName { get; set; }
    }

    public partial class Signer
    {
        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    //public partial class UserSignatures
    //{
    //    public static UserSignatures FromJson(string json) => JsonConvert.DeserializeObject<UserSignatures>(json, Signature.API.Model.Converter.Settings);
    //}

    //public static class Serialize
    //{
    //    public static string ToJson(this UserSignatures self) => JsonConvert.SerializeObject(self, Signature.API.Model.Converter.Settings);
    //}

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
