version: '3.4'

services:

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  websignatureclient:
    image: ${REGISTRY:-elefebvreoncontainers}/websignatureclient:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/WebSignatureClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12}
    depends_on:
      - rabbitmq   

  signature.api:
    image: ${REGISTRY:-elefebvreoncontainers}/signature.api:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Signature/Signature.API/Dockerfile    
    depends_on:
      - nosql.data
      - rabbitmq

  websignatureapigw:
    image: ${REGISTRY:-elefebvreoncontainers}/ocelotapigw:${PLATFORM:-linux}-${TAG:-dev}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - signature.api