{{- $name := include "apigwacc.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "ocelot-{{ $name }}"
  labels:
    app: {{ template "apigwacc.name" . }}
    chart: {{ template "apigwacc.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    env: {{ .Values.lef.env }}
    version: {{ .Chart.Version | quote }} 
data:
  {{ (.Files.Glob "configuration-account.json").AsConfig  | indent 2 }}

