{{- $name := include "lexon-api.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lexon-api.fullname" . }}
  labels:
    ufo: {{ $cfgname}}
    app: {{ template "lexon-api.name" . }}
    chart: {{ template "lexon-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    env: {{ .Values.lef.env }}
    version: {{ .Chart.Version | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "lexon-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "lexon-api.name" . }}
        release: {{ .Release.Name }}
      {{ if .Values.inf.mesh.enabled -}}
      annotations:
        linkerd.io/inject: enabled
      {{- end }}
    spec:
      {{ if .Values.inf.registry -}}
      imagePullSecrets:
      - name: {{ .Values.inf.registry.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ template "fqdn-image" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PATH_BASE
              value: {{ include "pathBase" . }}
            - name: k8sname
              value: {{ .Values.clusterName }}
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}
          {{- if .Values.env.configmap -}}
          {{- range .Values.env.configmap }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $cfgname }}
                  key: {{ .key }}
          {{- end -}}
          {{- end }}
            - name: EnvModels__0__conn
              valueFrom:
                secretKeyRef:
                  name: elefebvre-api-secrets
                  key: lexon_devs_conn
            - name: EnvModels__1__conn
              valueFrom:
                secretKeyRef:
                  name: elefebvre-api-secrets
                  key: lexon_dev_conn
            - name: EnvModels__2__conn
              valueFrom:
                secretKeyRef:
                  name: elefebvre-api-secrets
                  key: lexon_qa_conn
            - name: EnvModels__3__conn
              valueFrom:
                secretKeyRef:
                  name: elefebvre-api-secrets
                  key: lexon_pre_conn
            - name: EnvModels__4__conn
              valueFrom:
                secretKeyRef:
                  name: elefebvre-api-secrets
                  key: lexon_pro_conn                        
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

