version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine
      
  webportalclient:
    image: ${REGISTRY:-eshop}/webportalclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebPortalClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  webgoogleclient:
    image: ${REGISTRY:-eshop}/webgoogleclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebGoogleClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq

  webofficeclient:
    image: ${REGISTRY:-eshop}/webofficeclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebOffice365Client/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq
      
  weblexonclient:
    image: ${REGISTRY:-eshop}/weblexonclient:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebLexonClient/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    depends_on:
      - rabbitmq      

  account.api:
    image: ${REGISTRY:-eshop}/account.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Account/Account.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webaccountapigw:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - account.api

  lexon.api:
    image: ${REGISTRY:-eshop}/lexon.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  lexon.mysql.api:
    image: ${REGISTRY:-eshop}/lexon.mysql.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Lexon/Lexon.MySql/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq
      - lexon.api

  weblexonapigw:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
#      - ordering.api
#     - marketing.api
#     - catalog.api
#     - basket.api
#     - account.api
      - lexon.api
      - lexon.mysql.api